/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_e8commit_free: (a: number, b: number) => void;
export const __wbg_e8xe8commit_free: (a: number, b: number) => void;
export const __wbg_get_e8commit_c: (a: number) => number;
export const __wbg_get_e8commit_pi1: (a: number) => number;
export const __wbg_get_e8commit_pi2: (a: number) => number;
export const __wbg_get_e8commit_pi3: (a: number) => number;
export const __wbg_get_e8xe8commit_c2: (a: number) => number;
export const __wbg_get_e8xe8commit_combined: (a: number) => number;
export const __wbg_set_e8commit_c: (a: number, b: number) => void;
export const __wbg_set_e8commit_pi1: (a: number, b: number) => void;
export const __wbg_set_e8commit_pi2: (a: number, b: number) => void;
export const __wbg_set_e8commit_pi3: (a: number, b: number) => void;
export const __wbg_set_e8xe8commit_c2: (a: number, b: number) => void;
export const __wbg_set_e8xe8commit_combined: (a: number, b: number) => void;
export const e8_commit: (a: number, b: number) => [number, number, number];
export const e8x_e8_commit: (a: number, b: number, c: number, d: number) => [number, number, number];
export const e8xe8commit_c1_pi1: (a: number) => number;
export const e8xe8commit_c1_pi2: (a: number) => number;
export const e8xe8commit_c1_pi3: (a: number) => number;
export const e8xe8commit_c2_pi1: (a: number) => number;
export const e8xe8commit_c2_pi2: (a: number) => number;
export const e8xe8commit_c2_pi3: (a: number) => number;
export const modular_weight_check: (a: number, b: number) => number;
export const password_to_roots: (a: number, b: number) => [number, number];
export const theta0: (a: number) => number;
export const theta1: (a: number) => number;
export const theta2: (a: number) => number;
export const theta3: (a: number) => number;
export const __wbg_set_e8xe8commit_c1: (a: number, b: number) => void;
export const __wbg_get_e8xe8commit_c1: (a: number) => number;
export const theta0_prime: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
